# Generated by Django 3.0.5 on 2020-04-28 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('quote', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('published_date', models.DateField()),
                ('author', models.ManyToManyField(to='GoodBooksApp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('books', models.ManyToManyField(to='GoodBooksApp.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodBooksApp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodBooksApp.Profile')),
            ],
        ),
    ]
